=== ChromeDevTools/devtools-frontend/scripts/json_validator/module.schema.json
{
    "$schema": "http://json-schema.org/draft-04/schema#",
    "type": "object",
    "additionalProperties": false,
    "properties": {
        "extensions": {
            "type": "array",
            "description": "Extension points",
            "items": {
                "properties": {
                    "type": {"type": "string"},
                    "order": {"type": "number"}
                }
            }
        },
        "dependencies": {
            "type": "array",
            "items": {
                "type": "string"
            }
        },
        "scripts": {
            "type": "array",
            "items": {
                "type": "string"
            }
        },
        "resources": {
            "type": "array",
            "items": {
                "type": "string"
            }
        },
        "skip_compilation": {
            "type": "array",
            "items": {
                "type": "string"
            }
        },
        "experiment": {
            "type": "string"
        }
    },
    "definitions": {
    }
}

=== ChromeDevTools/devtools-frontend/front_end/mobile_throttling/module.json
{
    "extensions": [
        {
            "type": "setting",
            "settingName": "customNetworkConditions",
            "settingType": "array",
            "defaultValue": []
        },
        {
            "type": "@UI.ActionDelegate",
            "actionId": "network-conditions.network-offline",
            "category": "Network",
            "title": "Go offline",
            "className": "MobileThrottling.ThrottlingManager.ActionDelegate",
            "tags": "device"
        },
        {
            "type": "@UI.ActionDelegate",
            "actionId": "network-conditions.network-online",
            "category": "Network",
            "title": "Go online",
            "className": "MobileThrottling.ThrottlingManager.ActionDelegate",
            "tags": "device"
        },
        {
            "type": "view",
            "location": "settings-view",
            "id": "throttling-conditions",
            "title": "Throttling",
            "order": 35,
            "className": "MobileThrottling.ThrottlingSettingsTab",
            "settings": [
                "customNetworkConditions"
            ]
        }
    ],
    "dependencies": [
        "common",
        "sdk",
        "ui",
        "protocol"
    ],
    "scripts": [
        "ThrottlingPresets.js",
        "MobileThrottlingSelector.js",
        "NetworkThrottlingSelector.js",
        "ThrottlingSettingsTab.js",
        "ThrottlingManager.js"
    ],
    "resources": [
        "throttlingSettingsTab.css"
    ]
}
